# Generated by Django 4.2 on 2023-05-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_is_sub_category_sub_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
